//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cpp.test.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.coreSoap")]
    public interface coreSoap {
        
        // CODEGEN: Generating message contract since element name createMandateXmlStr from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateMandateRequest", ReplyAction="*")]
        cpp.test.ServiceReference1.CreateMandateRequestResponse CreateMandateRequest(cpp.test.ServiceReference1.CreateMandateRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateMandateRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<cpp.test.ServiceReference1.CreateMandateRequestResponse> CreateMandateRequestAsync(cpp.test.ServiceReference1.CreateMandateRequestRequest request);
        
        // CODEGEN: Generating message contract since element name cancelMandateXmlStr from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelMandateRequest", ReplyAction="*")]
        cpp.test.ServiceReference1.CancelMandateRequestResponse CancelMandateRequest(cpp.test.ServiceReference1.CancelMandateRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelMandateRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<cpp.test.ServiceReference1.CancelMandateRequestResponse> CancelMandateRequestAsync(cpp.test.ServiceReference1.CancelMandateRequestRequest request);
        
        // CODEGEN: Generating message contract since element name generateOtpXmlStr from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateOTPRequest", ReplyAction="*")]
        cpp.test.ServiceReference1.GenerateOTPRequestResponse GenerateOTPRequest(cpp.test.ServiceReference1.GenerateOTPRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateOTPRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<cpp.test.ServiceReference1.GenerateOTPRequestResponse> GenerateOTPRequestAsync(cpp.test.ServiceReference1.GenerateOTPRequestRequest request);
        
        // CODEGEN: Generating message contract since element name generateOtpWithoutCustomerValidationXmlStr from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateOTPWithoutCustomerValidationRequest", ReplyAction="*")]
        cpp.test.ServiceReference1.GenerateOTPWithoutCustomerValidationRequestResponse GenerateOTPWithoutCustomerValidationRequest(cpp.test.ServiceReference1.GenerateOTPWithoutCustomerValidationRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateOTPWithoutCustomerValidationRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<cpp.test.ServiceReference1.GenerateOTPWithoutCustomerValidationRequestResponse> GenerateOTPWithoutCustomerValidationRequestAsync(cpp.test.ServiceReference1.GenerateOTPWithoutCustomerValidationRequestRequest request);
        
        // CODEGEN: Generating message contract since element name validateOtpXmlStr from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateOTPRequest", ReplyAction="*")]
        cpp.test.ServiceReference1.ValidateOTPRequestResponse ValidateOTPRequest(cpp.test.ServiceReference1.ValidateOTPRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateOTPRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<cpp.test.ServiceReference1.ValidateOTPRequestResponse> ValidateOTPRequestAsync(cpp.test.ServiceReference1.ValidateOTPRequestRequest request);
        
        // CODEGEN: Generating message contract since element name validateOtpWithoutCustomerValidationXmlStr from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateOTPWithoutCustomerValidationRequest", ReplyAction="*")]
        cpp.test.ServiceReference1.ValidateOTPWithoutCustomerValidationRequestResponse ValidateOTPWithoutCustomerValidationRequest(cpp.test.ServiceReference1.ValidateOTPWithoutCustomerValidationRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateOTPWithoutCustomerValidationRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<cpp.test.ServiceReference1.ValidateOTPWithoutCustomerValidationRequestResponse> ValidateOTPWithoutCustomerValidationRequestAsync(cpp.test.ServiceReference1.ValidateOTPWithoutCustomerValidationRequestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateMandateRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateMandateRequest", Namespace="http://tempuri.org/", Order=0)]
        public cpp.test.ServiceReference1.CreateMandateRequestRequestBody Body;
        
        public CreateMandateRequestRequest() {
        }
        
        public CreateMandateRequestRequest(cpp.test.ServiceReference1.CreateMandateRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateMandateRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string createMandateXmlStr;
        
        public CreateMandateRequestRequestBody() {
        }
        
        public CreateMandateRequestRequestBody(string createMandateXmlStr) {
            this.createMandateXmlStr = createMandateXmlStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateMandateRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateMandateRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public cpp.test.ServiceReference1.CreateMandateRequestResponseBody Body;
        
        public CreateMandateRequestResponse() {
        }
        
        public CreateMandateRequestResponse(cpp.test.ServiceReference1.CreateMandateRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateMandateRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateMandateRequestResult;
        
        public CreateMandateRequestResponseBody() {
        }
        
        public CreateMandateRequestResponseBody(string CreateMandateRequestResult) {
            this.CreateMandateRequestResult = CreateMandateRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelMandateRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelMandateRequest", Namespace="http://tempuri.org/", Order=0)]
        public cpp.test.ServiceReference1.CancelMandateRequestRequestBody Body;
        
        public CancelMandateRequestRequest() {
        }
        
        public CancelMandateRequestRequest(cpp.test.ServiceReference1.CancelMandateRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelMandateRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cancelMandateXmlStr;
        
        public CancelMandateRequestRequestBody() {
        }
        
        public CancelMandateRequestRequestBody(string cancelMandateXmlStr) {
            this.cancelMandateXmlStr = cancelMandateXmlStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelMandateRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelMandateRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public cpp.test.ServiceReference1.CancelMandateRequestResponseBody Body;
        
        public CancelMandateRequestResponse() {
        }
        
        public CancelMandateRequestResponse(cpp.test.ServiceReference1.CancelMandateRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelMandateRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CancelMandateRequestResult;
        
        public CancelMandateRequestResponseBody() {
        }
        
        public CancelMandateRequestResponseBody(string CancelMandateRequestResult) {
            this.CancelMandateRequestResult = CancelMandateRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateOTPRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateOTPRequest", Namespace="http://tempuri.org/", Order=0)]
        public cpp.test.ServiceReference1.GenerateOTPRequestRequestBody Body;
        
        public GenerateOTPRequestRequest() {
        }
        
        public GenerateOTPRequestRequest(cpp.test.ServiceReference1.GenerateOTPRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateOTPRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string generateOtpXmlStr;
        
        public GenerateOTPRequestRequestBody() {
        }
        
        public GenerateOTPRequestRequestBody(string generateOtpXmlStr) {
            this.generateOtpXmlStr = generateOtpXmlStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateOTPRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateOTPRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public cpp.test.ServiceReference1.GenerateOTPRequestResponseBody Body;
        
        public GenerateOTPRequestResponse() {
        }
        
        public GenerateOTPRequestResponse(cpp.test.ServiceReference1.GenerateOTPRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateOTPRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GenerateOTPRequestResult;
        
        public GenerateOTPRequestResponseBody() {
        }
        
        public GenerateOTPRequestResponseBody(string GenerateOTPRequestResult) {
            this.GenerateOTPRequestResult = GenerateOTPRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateOTPWithoutCustomerValidationRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateOTPWithoutCustomerValidationRequest", Namespace="http://tempuri.org/", Order=0)]
        public cpp.test.ServiceReference1.GenerateOTPWithoutCustomerValidationRequestRequestBody Body;
        
        public GenerateOTPWithoutCustomerValidationRequestRequest() {
        }
        
        public GenerateOTPWithoutCustomerValidationRequestRequest(cpp.test.ServiceReference1.GenerateOTPWithoutCustomerValidationRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateOTPWithoutCustomerValidationRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string generateOtpWithoutCustomerValidationXmlStr;
        
        public GenerateOTPWithoutCustomerValidationRequestRequestBody() {
        }
        
        public GenerateOTPWithoutCustomerValidationRequestRequestBody(string generateOtpWithoutCustomerValidationXmlStr) {
            this.generateOtpWithoutCustomerValidationXmlStr = generateOtpWithoutCustomerValidationXmlStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateOTPWithoutCustomerValidationRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateOTPWithoutCustomerValidationRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public cpp.test.ServiceReference1.GenerateOTPWithoutCustomerValidationRequestResponseBody Body;
        
        public GenerateOTPWithoutCustomerValidationRequestResponse() {
        }
        
        public GenerateOTPWithoutCustomerValidationRequestResponse(cpp.test.ServiceReference1.GenerateOTPWithoutCustomerValidationRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateOTPWithoutCustomerValidationRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GenerateOTPWithoutCustomerValidationRequestResult;
        
        public GenerateOTPWithoutCustomerValidationRequestResponseBody() {
        }
        
        public GenerateOTPWithoutCustomerValidationRequestResponseBody(string GenerateOTPWithoutCustomerValidationRequestResult) {
            this.GenerateOTPWithoutCustomerValidationRequestResult = GenerateOTPWithoutCustomerValidationRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateOTPRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateOTPRequest", Namespace="http://tempuri.org/", Order=0)]
        public cpp.test.ServiceReference1.ValidateOTPRequestRequestBody Body;
        
        public ValidateOTPRequestRequest() {
        }
        
        public ValidateOTPRequestRequest(cpp.test.ServiceReference1.ValidateOTPRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateOTPRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string validateOtpXmlStr;
        
        public ValidateOTPRequestRequestBody() {
        }
        
        public ValidateOTPRequestRequestBody(string validateOtpXmlStr) {
            this.validateOtpXmlStr = validateOtpXmlStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateOTPRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateOTPRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public cpp.test.ServiceReference1.ValidateOTPRequestResponseBody Body;
        
        public ValidateOTPRequestResponse() {
        }
        
        public ValidateOTPRequestResponse(cpp.test.ServiceReference1.ValidateOTPRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateOTPRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ValidateOTPRequestResult;
        
        public ValidateOTPRequestResponseBody() {
        }
        
        public ValidateOTPRequestResponseBody(string ValidateOTPRequestResult) {
            this.ValidateOTPRequestResult = ValidateOTPRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateOTPWithoutCustomerValidationRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateOTPWithoutCustomerValidationRequest", Namespace="http://tempuri.org/", Order=0)]
        public cpp.test.ServiceReference1.ValidateOTPWithoutCustomerValidationRequestRequestBody Body;
        
        public ValidateOTPWithoutCustomerValidationRequestRequest() {
        }
        
        public ValidateOTPWithoutCustomerValidationRequestRequest(cpp.test.ServiceReference1.ValidateOTPWithoutCustomerValidationRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateOTPWithoutCustomerValidationRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string validateOtpWithoutCustomerValidationXmlStr;
        
        public ValidateOTPWithoutCustomerValidationRequestRequestBody() {
        }
        
        public ValidateOTPWithoutCustomerValidationRequestRequestBody(string validateOtpWithoutCustomerValidationXmlStr) {
            this.validateOtpWithoutCustomerValidationXmlStr = validateOtpWithoutCustomerValidationXmlStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateOTPWithoutCustomerValidationRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateOTPWithoutCustomerValidationRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public cpp.test.ServiceReference1.ValidateOTPWithoutCustomerValidationRequestResponseBody Body;
        
        public ValidateOTPWithoutCustomerValidationRequestResponse() {
        }
        
        public ValidateOTPWithoutCustomerValidationRequestResponse(cpp.test.ServiceReference1.ValidateOTPWithoutCustomerValidationRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateOTPWithoutCustomerValidationRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ValidateOTPWithoutCustomerValidationRequestResult;
        
        public ValidateOTPWithoutCustomerValidationRequestResponseBody() {
        }
        
        public ValidateOTPWithoutCustomerValidationRequestResponseBody(string ValidateOTPWithoutCustomerValidationRequestResult) {
            this.ValidateOTPWithoutCustomerValidationRequestResult = ValidateOTPWithoutCustomerValidationRequestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface coreSoapChannel : cpp.test.ServiceReference1.coreSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class coreSoapClient : System.ServiceModel.ClientBase<cpp.test.ServiceReference1.coreSoap>, cpp.test.ServiceReference1.coreSoap {
        
        public coreSoapClient() {
        }
        
        public coreSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public coreSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public coreSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public coreSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cpp.test.ServiceReference1.CreateMandateRequestResponse cpp.test.ServiceReference1.coreSoap.CreateMandateRequest(cpp.test.ServiceReference1.CreateMandateRequestRequest request) {
            return base.Channel.CreateMandateRequest(request);
        }
        
        public string CreateMandateRequest(string createMandateXmlStr) {
            cpp.test.ServiceReference1.CreateMandateRequestRequest inValue = new cpp.test.ServiceReference1.CreateMandateRequestRequest();
            inValue.Body = new cpp.test.ServiceReference1.CreateMandateRequestRequestBody();
            inValue.Body.createMandateXmlStr = createMandateXmlStr;
            cpp.test.ServiceReference1.CreateMandateRequestResponse retVal = ((cpp.test.ServiceReference1.coreSoap)(this)).CreateMandateRequest(inValue);
            return retVal.Body.CreateMandateRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<cpp.test.ServiceReference1.CreateMandateRequestResponse> cpp.test.ServiceReference1.coreSoap.CreateMandateRequestAsync(cpp.test.ServiceReference1.CreateMandateRequestRequest request) {
            return base.Channel.CreateMandateRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<cpp.test.ServiceReference1.CreateMandateRequestResponse> CreateMandateRequestAsync(string createMandateXmlStr) {
            cpp.test.ServiceReference1.CreateMandateRequestRequest inValue = new cpp.test.ServiceReference1.CreateMandateRequestRequest();
            inValue.Body = new cpp.test.ServiceReference1.CreateMandateRequestRequestBody();
            inValue.Body.createMandateXmlStr = createMandateXmlStr;
            return ((cpp.test.ServiceReference1.coreSoap)(this)).CreateMandateRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cpp.test.ServiceReference1.CancelMandateRequestResponse cpp.test.ServiceReference1.coreSoap.CancelMandateRequest(cpp.test.ServiceReference1.CancelMandateRequestRequest request) {
            return base.Channel.CancelMandateRequest(request);
        }
        
        public string CancelMandateRequest(string cancelMandateXmlStr) {
            cpp.test.ServiceReference1.CancelMandateRequestRequest inValue = new cpp.test.ServiceReference1.CancelMandateRequestRequest();
            inValue.Body = new cpp.test.ServiceReference1.CancelMandateRequestRequestBody();
            inValue.Body.cancelMandateXmlStr = cancelMandateXmlStr;
            cpp.test.ServiceReference1.CancelMandateRequestResponse retVal = ((cpp.test.ServiceReference1.coreSoap)(this)).CancelMandateRequest(inValue);
            return retVal.Body.CancelMandateRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<cpp.test.ServiceReference1.CancelMandateRequestResponse> cpp.test.ServiceReference1.coreSoap.CancelMandateRequestAsync(cpp.test.ServiceReference1.CancelMandateRequestRequest request) {
            return base.Channel.CancelMandateRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<cpp.test.ServiceReference1.CancelMandateRequestResponse> CancelMandateRequestAsync(string cancelMandateXmlStr) {
            cpp.test.ServiceReference1.CancelMandateRequestRequest inValue = new cpp.test.ServiceReference1.CancelMandateRequestRequest();
            inValue.Body = new cpp.test.ServiceReference1.CancelMandateRequestRequestBody();
            inValue.Body.cancelMandateXmlStr = cancelMandateXmlStr;
            return ((cpp.test.ServiceReference1.coreSoap)(this)).CancelMandateRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cpp.test.ServiceReference1.GenerateOTPRequestResponse cpp.test.ServiceReference1.coreSoap.GenerateOTPRequest(cpp.test.ServiceReference1.GenerateOTPRequestRequest request) {
            return base.Channel.GenerateOTPRequest(request);
        }
        
        public string GenerateOTPRequest(string generateOtpXmlStr) {
            cpp.test.ServiceReference1.GenerateOTPRequestRequest inValue = new cpp.test.ServiceReference1.GenerateOTPRequestRequest();
            inValue.Body = new cpp.test.ServiceReference1.GenerateOTPRequestRequestBody();
            inValue.Body.generateOtpXmlStr = generateOtpXmlStr;
            cpp.test.ServiceReference1.GenerateOTPRequestResponse retVal = ((cpp.test.ServiceReference1.coreSoap)(this)).GenerateOTPRequest(inValue);
            return retVal.Body.GenerateOTPRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<cpp.test.ServiceReference1.GenerateOTPRequestResponse> cpp.test.ServiceReference1.coreSoap.GenerateOTPRequestAsync(cpp.test.ServiceReference1.GenerateOTPRequestRequest request) {
            return base.Channel.GenerateOTPRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<cpp.test.ServiceReference1.GenerateOTPRequestResponse> GenerateOTPRequestAsync(string generateOtpXmlStr) {
            cpp.test.ServiceReference1.GenerateOTPRequestRequest inValue = new cpp.test.ServiceReference1.GenerateOTPRequestRequest();
            inValue.Body = new cpp.test.ServiceReference1.GenerateOTPRequestRequestBody();
            inValue.Body.generateOtpXmlStr = generateOtpXmlStr;
            return ((cpp.test.ServiceReference1.coreSoap)(this)).GenerateOTPRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cpp.test.ServiceReference1.GenerateOTPWithoutCustomerValidationRequestResponse cpp.test.ServiceReference1.coreSoap.GenerateOTPWithoutCustomerValidationRequest(cpp.test.ServiceReference1.GenerateOTPWithoutCustomerValidationRequestRequest request) {
            return base.Channel.GenerateOTPWithoutCustomerValidationRequest(request);
        }
        
        public string GenerateOTPWithoutCustomerValidationRequest(string generateOtpWithoutCustomerValidationXmlStr) {
            cpp.test.ServiceReference1.GenerateOTPWithoutCustomerValidationRequestRequest inValue = new cpp.test.ServiceReference1.GenerateOTPWithoutCustomerValidationRequestRequest();
            inValue.Body = new cpp.test.ServiceReference1.GenerateOTPWithoutCustomerValidationRequestRequestBody();
            inValue.Body.generateOtpWithoutCustomerValidationXmlStr = generateOtpWithoutCustomerValidationXmlStr;
            cpp.test.ServiceReference1.GenerateOTPWithoutCustomerValidationRequestResponse retVal = ((cpp.test.ServiceReference1.coreSoap)(this)).GenerateOTPWithoutCustomerValidationRequest(inValue);
            return retVal.Body.GenerateOTPWithoutCustomerValidationRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<cpp.test.ServiceReference1.GenerateOTPWithoutCustomerValidationRequestResponse> cpp.test.ServiceReference1.coreSoap.GenerateOTPWithoutCustomerValidationRequestAsync(cpp.test.ServiceReference1.GenerateOTPWithoutCustomerValidationRequestRequest request) {
            return base.Channel.GenerateOTPWithoutCustomerValidationRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<cpp.test.ServiceReference1.GenerateOTPWithoutCustomerValidationRequestResponse> GenerateOTPWithoutCustomerValidationRequestAsync(string generateOtpWithoutCustomerValidationXmlStr) {
            cpp.test.ServiceReference1.GenerateOTPWithoutCustomerValidationRequestRequest inValue = new cpp.test.ServiceReference1.GenerateOTPWithoutCustomerValidationRequestRequest();
            inValue.Body = new cpp.test.ServiceReference1.GenerateOTPWithoutCustomerValidationRequestRequestBody();
            inValue.Body.generateOtpWithoutCustomerValidationXmlStr = generateOtpWithoutCustomerValidationXmlStr;
            return ((cpp.test.ServiceReference1.coreSoap)(this)).GenerateOTPWithoutCustomerValidationRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cpp.test.ServiceReference1.ValidateOTPRequestResponse cpp.test.ServiceReference1.coreSoap.ValidateOTPRequest(cpp.test.ServiceReference1.ValidateOTPRequestRequest request) {
            return base.Channel.ValidateOTPRequest(request);
        }
        
        public string ValidateOTPRequest(string validateOtpXmlStr) {
            cpp.test.ServiceReference1.ValidateOTPRequestRequest inValue = new cpp.test.ServiceReference1.ValidateOTPRequestRequest();
            inValue.Body = new cpp.test.ServiceReference1.ValidateOTPRequestRequestBody();
            inValue.Body.validateOtpXmlStr = validateOtpXmlStr;
            cpp.test.ServiceReference1.ValidateOTPRequestResponse retVal = ((cpp.test.ServiceReference1.coreSoap)(this)).ValidateOTPRequest(inValue);
            return retVal.Body.ValidateOTPRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<cpp.test.ServiceReference1.ValidateOTPRequestResponse> cpp.test.ServiceReference1.coreSoap.ValidateOTPRequestAsync(cpp.test.ServiceReference1.ValidateOTPRequestRequest request) {
            return base.Channel.ValidateOTPRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<cpp.test.ServiceReference1.ValidateOTPRequestResponse> ValidateOTPRequestAsync(string validateOtpXmlStr) {
            cpp.test.ServiceReference1.ValidateOTPRequestRequest inValue = new cpp.test.ServiceReference1.ValidateOTPRequestRequest();
            inValue.Body = new cpp.test.ServiceReference1.ValidateOTPRequestRequestBody();
            inValue.Body.validateOtpXmlStr = validateOtpXmlStr;
            return ((cpp.test.ServiceReference1.coreSoap)(this)).ValidateOTPRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        cpp.test.ServiceReference1.ValidateOTPWithoutCustomerValidationRequestResponse cpp.test.ServiceReference1.coreSoap.ValidateOTPWithoutCustomerValidationRequest(cpp.test.ServiceReference1.ValidateOTPWithoutCustomerValidationRequestRequest request) {
            return base.Channel.ValidateOTPWithoutCustomerValidationRequest(request);
        }
        
        public string ValidateOTPWithoutCustomerValidationRequest(string validateOtpWithoutCustomerValidationXmlStr) {
            cpp.test.ServiceReference1.ValidateOTPWithoutCustomerValidationRequestRequest inValue = new cpp.test.ServiceReference1.ValidateOTPWithoutCustomerValidationRequestRequest();
            inValue.Body = new cpp.test.ServiceReference1.ValidateOTPWithoutCustomerValidationRequestRequestBody();
            inValue.Body.validateOtpWithoutCustomerValidationXmlStr = validateOtpWithoutCustomerValidationXmlStr;
            cpp.test.ServiceReference1.ValidateOTPWithoutCustomerValidationRequestResponse retVal = ((cpp.test.ServiceReference1.coreSoap)(this)).ValidateOTPWithoutCustomerValidationRequest(inValue);
            return retVal.Body.ValidateOTPWithoutCustomerValidationRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<cpp.test.ServiceReference1.ValidateOTPWithoutCustomerValidationRequestResponse> cpp.test.ServiceReference1.coreSoap.ValidateOTPWithoutCustomerValidationRequestAsync(cpp.test.ServiceReference1.ValidateOTPWithoutCustomerValidationRequestRequest request) {
            return base.Channel.ValidateOTPWithoutCustomerValidationRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<cpp.test.ServiceReference1.ValidateOTPWithoutCustomerValidationRequestResponse> ValidateOTPWithoutCustomerValidationRequestAsync(string validateOtpWithoutCustomerValidationXmlStr) {
            cpp.test.ServiceReference1.ValidateOTPWithoutCustomerValidationRequestRequest inValue = new cpp.test.ServiceReference1.ValidateOTPWithoutCustomerValidationRequestRequest();
            inValue.Body = new cpp.test.ServiceReference1.ValidateOTPWithoutCustomerValidationRequestRequestBody();
            inValue.Body.validateOtpWithoutCustomerValidationXmlStr = validateOtpWithoutCustomerValidationXmlStr;
            return ((cpp.test.ServiceReference1.coreSoap)(this)).ValidateOTPWithoutCustomerValidationRequestAsync(inValue);
        }
    }
}
