//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralPayPlusBridge.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentralPayOtp
    {
        public long Id { get; set; }
        public long MandateCodeId { get; set; }
        public string ReferenceNumber { get; set; }
        public string otp { get; set; }
        public System.DateTime DateGenerated { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public Nullable<System.DateTime> DateUsed { get; set; }
    
        public virtual MandateLog MandateLog { get; set; }
    }
}
