//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralPayPlusBridge.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MandateLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MandateLog()
        {
            this.CentralPayOtps = new HashSet<CentralPayOtp>();
        }
    
        public long Id { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public string BankCode { get; set; }
        public string TransType { get; set; }
        public string BillerId { get; set; }
        public string BillerName { get; set; }
        public string BillerTransId { get; set; }
        public string HashValue { get; set; }
        public string MandateCode { get; set; }
        public string ResponseCode { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public bool IsCancelled { get; set; }
        public Nullable<System.DateTime> DateCancelled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CentralPayOtp> CentralPayOtps { get; set; }
    }
}
